### ISSUE TITLE
Why it does not work for me?

### ISSUE THREAD

**Issue by jufei** [swapnil-linux/ansible#1]
hi:

I used your script to try to filter out hosts which is reacable, but it does not work;

my scrpt:

---
- name: check reachable hosts
  hosts: "113"
  gather_facts: no
  tasks:
    - command: ping -c1 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result|success

result:

PLAY [check reachable hosts] **************************************************************************************************************************************************************************************

TASK [command] ****************************************************************************************************************************************************************************************************
changed: [10.69.64.113 -> localhost]

TASK [group_by] ***************************************************************************************************************************************************************************************************
fatal: [10.69.64.113]: FAILED! => {"msg": "The conditional check 'ping_result|success' failed. The error was: template error while templating string: no filter named 'success'. String: {% if ping_result|success %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/work/tacase_dev/Resource/smartta/test.yaml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      ignore_errors: yes\n    - group_by: key=reachable\n      ^ here\n"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
10.69.64.113               : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

my env:
ansible-playbook 2.9.2
why?
Thanks.

**Comment by swapnil-linux** [comment]
`when: ping_result|success` wont work with ansible 2.9 changing it to `when: ping_result is success` worked. I'll fix it.

**Comment by swapnil-linux** [comment]
I'll close the issue once you confirm. Thanks for reporting.

**Comment by jufei** [comment]
Thanks
